from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, \
    LongType, StringType, BooleanType, IntegerType

spark = SparkSession.builder \
    .appName("Huy dep zai") \
    .master("local[*]") \
    .config("spark.executor.memory", "4g") \
    .getOrCreate()

schema = StructType([
    StructField("id", StringType(),True),
    StructField("type", StringType(),True),
    StructField("actor", StructType([
        StructField("id", LongType(), True),
        StructField("login", StringType(), True),
        StructField("gravatar_id", StringType(), True),
        StructField("url", StringType(), True),
        StructField("avatar_url", StringType(), True),
    ])),
    StructField("repo", StructType([
        StructField("id", LongType(), True),
        StructField("name", StringType(), True),
        StructField("url", StringType(), True)
    ]), True),
    StructField("payload", StructType([
        StructField("action", StringType(), True),
        StructField("number", IntegerType(), True),
        StructField("pull_request", StructType([
            StructField("url", StringType(), True),
            StructField("id", LongType(), True),
            StructField("html_url", StringType(), True),
            StructField("diff_url", StringType(), True),
            StructField("patch_url", StringType(), True),
            StructField("issue_url", StringType(), True),
            StructField("number", IntegerType(), True),
            StructField("state", StringType(), True),
            StructField("locked", BooleanType(), True),
            StructField("title", StringType(), True),
            StructField("user", StructType([
                StructField("login", StringType(), True),
                StructField("id", LongType(), True),
                StructField("avatar_url", StringType(), True),
                StructField("gravatar_id", StringType(), True),
                StructField("url", StringType(), True),
                StructField("html_url", StringType(), True),
                StructField("followers_url", IntegerType(), True),
                StructField("following_url", StringType(), True),
                StructField("gists_url", BooleanType(), True),
                StructField("starred_url", StringType(), True),
                StructField("subscriptions_url", StringType(), True),
                StructField("organizations_url", LongType(), True),
                StructField("repos_url", StringType(), True),
                StructField("events_url", StringType(), True),
                StructField("received_events_url", StringType(), True),
                StructField("type", StringType(), True),
                StructField("site_admin", BooleanType(), True),
            ]), True),
            StructField("body", StringType(), True),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
            StructField("closed_at", StringType(), True),
            StructField("merged_at", StringType(), True),
            StructField("merge_commit_sha", StringType(), True),
            StructField("assignee", StringType(), True),
            StructField("milestone", StringType(), True),
            StructField("commits_url", StringType(), True),
            StructField("review_comments_url", StringType(), True),
            StructField("review_comment_url", StringType(), True),
            StructField("comments_url", StringType(), True),
            StructField("statuses_url", StringType(), True),
            StructField("head", StructType([
                StructField("label", StringType(), True),
                StructField("ref", StringType(), True),
                StructField("sha", BooleanType(), True),
                StructField("user", StructType([
                    StructField("login", StringType(), True),
                    StructField("id", LongType(), True),
                    StructField("avatar_url", StringType(), True),
                    StructField("gravatar_id", StringType(), True),
                    StructField("url", StringType(), True),
                    StructField("html_url", StringType(), True),
                    StructField("followers_url", StringType(), True),
                    StructField("following_url", StringType(), True),
                    StructField("gists_url", StringType(), True),
                    StructField("starred_url", StringType(), True),
                    StructField("subscriptions_url", StringType(), True),
                    StructField("organizations_url", StringType(), True),
                    StructField("repos_url", StringType(), True),
                    StructField("events_url", StringType(), True),
                    StructField("received_events_url", StringType(), True),
                    StructField("type", StringType(), True),
                    StructField("site_admin", BooleanType(), True),
                ]), True),
                StructField("repo", StructType([
                    StructField("id", StringType(), True),
                    StructField("name", StringType(), True),
                    StructField("full_name", StringType(), True),
                    StructField("owner", StructType([
                        StructField("login", StringType(), True),
                        StructField("id", LongType(), True),
                        StructField("avatar_url", StringType(), True),
                        StructField("gravatar_id", StringType(), True),
                        StructField("url", StringType(), True),
                        StructField("html_url", StringType(), True),
                        StructField("followers_url", StringType(), True),
                        StructField("following_url", StringType(), True),
                        StructField("gists_url", StringType(), True),
                        StructField("starred_url", StringType(), True),
                        StructField("subscriptions_url", StringType(), True),
                        StructField("organizations_url", StringType(), True),
                        StructField("repos_url", StringType(), True),
                        StructField("events_url", StringType(), True),
                        StructField("received_events_url", StringType(), True),
                        StructField("type", StringType(), True),
                        StructField("site_admin", BooleanType(), True),
                    ]), True),
                    StructField("private", BooleanType(), True),
                    StructField("html_url", StringType(), True),
                    StructField("description", StringType(), True),
                    StructField("fork", StringType(), True),
                    StructField("url", StringType(), True),
                    StructField("forks_url", StringType(), True),
                    StructField("keys_url", StringType(), True),
                    StructField("collaborators_url", StringType(), True),
                    StructField("teams_url", StringType(), True),
                    StructField("hooks_url", StringType(), True),
                    StructField("issue_events_url", StringType(), True),
                    StructField("events_url", StringType(), True),
                    StructField("assignees_url", StringType(), True),
                    StructField("branches_url", StringType(), True),
                    StructField("tags_url", StringType(), True),
                    StructField("blobs_url", StringType(), True),
                    StructField("git_tags_url", StringType(), True),
                    StructField("git_refs_url", StringType(), True),
                    StructField("trees_url", StringType(), True),
                    StructField("statuses_url", StringType(), True),
                    StructField("languages_url", StringType(), True),
                    StructField("stargazers_url", StringType(), True),
                    StructField("contributors_url", StringType(), True),
                    StructField("subscribers_url", StringType(), True),
                    StructField("subscription_url", StringType(), True),
                    StructField("git_commits_url", StringType(), True),
                    StructField("comments_url", StringType(), True),
                    StructField("issue_comment_url", StringType(), True),
                    StructField("contents_url", StringType(), True),
                    StructField("compare_url", StringType(), True),
                    StructField("merges_url", StringType(), True),
                    StructField("archive_url", StringType(), True),
                    StructField("downloads_url", StringType(), True),
                    StructField("issues_url", StringType(), True),
                    StructField("pulls_url", StringType(), True),
                    StructField("milestones_url", StringType(), True),
                    StructField("notifications_url", StringType(), True),
                    StructField("releases_url", StringType(), True),
                    StructField("labels_url", StringType(), True),
                    StructField("created_at", StringType(), True),
                    StructField("updated_at", StringType(), True),
                    StructField("pushed_at", StringType(), True),
                    StructField("git_url", StringType(), True),
                    StructField("ssh_url", StringType(), True),
                    StructField("clone_url", StringType(), True),
                    StructField("svn_url", StringType(), True),
                    StructField("homepage", StringType(), True),
                    StructField("size", IntegerType(), True),
                    StructField("stargazers_count", IntegerType(), True),
                    StructField("language", StringType(), True),
                    StructField("has_issues", BooleanType(), True),
                    StructField("has_downloads", BooleanType(), True),
                    StructField("has_wiki", BooleanType(), True),
                    StructField("mirror_url", BooleanType(), True),
                    StructField("open_issues_count", IntegerType(), True),
                    StructField("forks", IntegerType(), True),
                    StructField("open_issues", IntegerType(), True),
                    StructField("watchers", IntegerType(), True),
                    StructField("default_branch", StringType(), True),
                ]), True)
            ]), True),
            StructField("base", StructType([
                StructField("label", StringType(), True),
                StructField("ref", StringType(), True),
                StructField("sha", BooleanType(), True),
                StructField("user", StructType([
                    StructField("login", StringType(), True),
                    StructField("id", LongType(), True),
                    StructField("avatar_url", StringType(), True),
                    StructField("gravatar_id", StringType(), True),
                    StructField("url", StringType(), True),
                    StructField("html_url", StringType(), True),
                    StructField("followers_url", StringType(), True),
                    StructField("following_url", StringType(), True),
                    StructField("gists_url", StringType(), True),
                    StructField("starred_url", StringType(), True),
                    StructField("subscriptions_url", StringType(), True),
                    StructField("organizations_url", StringType(), True),
                    StructField("repos_url", StringType(), True),
                    StructField("events_url", StringType(), True),
                    StructField("received_events_url", StringType(), True),
                    StructField("type", StringType(), True),
                    StructField("site_admin", BooleanType(), True),
                ]), True),
            ]), True),
        ]), True),
        StructField("ref", StringType(), True),
        StructField("ref_type", StringType(), True),
        StructField("master_branch", StringType(), True),
        StructField("description", StringType(), True),
        StructField("pusher_type", StringType(), True),
    ])),
    StructField("public", BooleanType(), True),
    StructField("created_at", StringType(), True)
])

df = spark.read.\
    option("multiline", "true").\
    schema(schema).\
<<<<<<< HEAD
    json("/home/miguel/HUY/Work/COURSE/DE_DA/DE_Anh Dat/Spark/study/Course_anh_dat /Resources/large-file.json")
=======
    json("/home/miguel/HUY/Work/COURSE/DE_DA/DE_Anh Dat/Spark/study/Course_anh_dat /resources/large-file.json")
>>>>>>> 2edff36 (commit of 04/04/2025 - problem 1)
df.show(truncate=False)